# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  #config.vm.box = "ubuntu/bionic64" 
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.disk :disk, size: "30GB", primary: true
  config.vm.box_check_update = false
  config.vm.provider "virtualbox" do |vb|
#    vb.cpus = 1
#    vb.memory = 768
  end

  (0..0).each do |i|
    config.vm.define "nfs-server-#{i}" do |node|
      node.vm.hostname = "nfs-server-#{i}"
      node.vm.network "private_network", ip: "192.168.10.1#{i}"
      node.vm.provision :hosts, :sync_hosts => true
      node.vm.provider "virtualbox" do |vb|
        vb.name = "nfs-server-#{i}"
        vb.cpus = 2
        vb.memory = 2048
        vb.customize ["modifyvm", :id, "--groups", "/UBUNTU-NFS-SERVER"]

      end
      # trigger reload
      #config.vm.provision 'shell', reboot: true
      
    end
  end

  (0..0).each do |i|
    config.vm.define "nfs-client-#{i}" do |node|
      node.vm.hostname = "nfs-client-#{i}"
      node.vm.network "private_network", ip: "192.168.10.2#{i}"
      node.vm.provision :hosts, :sync_hosts => true
      node.vm.provider "virtualbox" do |vb|
        vb.name = "nfs-client-#{i}"
        vb.cpus = 2
        vb.memory = 2048
        vb.customize ["modifyvm", :id, "--groups", "/UBUNTU-NFS-SERVER"]
      end
      
      # trigger reload
      #config.vm.provision 'shell', reboot: true
      
    end
  end
end
